version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: laravel_nginx_admin_client
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html:delegated
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app-admin-client
        container_name: laravel_app_admin_client
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel-admin-client
            - DB_USERNAME=root
            - DB_PASSWORD=password
        user: "${UID:-1000}:${GID:-1000}"

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql_admin_client
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel-admin-client
        ports:
            - "3307:3306"
        volumes:
            - mysql_data_product:/var/lib/mysql



volumes:
    mysql_data_product:

